### ISSUE TITLE
Specify minimum NodeJS version

### ISSUE THREAD

**Issue by geoand** [snowdrop/github-repo-cleanup-scripts#1]
It would help to provide the minimum required NodeJS version in the README.

If we are to use Openshift s2i to create an image, it [seems](https://docs.openshift.com/container-platform/3.9/using_images/s2i_images/nodejs.html#nodejs-versions) that the project needs to be able to run with NodeJS 6

**Comment by geoand** [comment]
I see however from one of the NodeJS [boosters](https://github.com/bucharest-gold/nodejs-health-check/blob/master/.openshiftio/application.yaml) that they are using Node 10.x, so I guess the Node version is not a problem :)

**Comment by lincolnthree** [comment]
Hmmm... this could probably be enforce in package.json if it's an issue.

**Comment by geoand** [comment]
It probably won't be.

**Comment by lincolnthree** [comment]
Done.
