### ISSUE TITLE
Make configuration more flexible

### ISSUE THREAD

**Issue by geoand** [snowdrop/github-repo-cleanup-scripts#2]
It would be good if the configuration was more flexible, for example allowing us to pass environment variables instead of needing to create the file.
Environment variables are probably the easiest way to use Kubernetes / Openshift [secrets](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)

Perhaps the [nconf](https://github.com/indexzero/nconf) module would be useful

**Comment by lincolnthree** [comment]
Done.
